In [9]:
import numpy as np

In [10]:
matriz_A = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [11]:
print(matriz_A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
matriz_A[0] # Acessar primeira linha

array([1, 2, 3])

In [13]:
matriz_A[0][2] # Acessar terceira coluna da primeira linha

3

- Transposição de matriz: operação que troca as linhas e colunas da matriz.

In [14]:
matriz_transposta = matriz_A.transpose()
matriz_transposta

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

- Adição de matrizes:

In [15]:
matriz1 = np.array([[1,2,3], [4,5,6], [7,8,9]])
matriz2 = np.array([[9,8,7], [6,5,4], [3,2,1]])
matriz1 + matriz2

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

- Subtração de matrizes:

In [19]:
matriz1 - matriz2

array([[-8, -6, -4],
       [-2,  0,  2],
       [ 4,  6,  8]])

- Multiplicação de matrizes:

In [18]:
np.dot(matriz1, matriz2)

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])