### Matriz Transposta

In [1]:
import numpy as np

In [3]:
matriz = np.array([[1,2,3], [4,5,6], [7,8,9]])
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
matriz.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

### Matriz Inversa
Para uma matriz ter matriz inversa precisa:
- Ser matriz quadrada (nxn)
- Ter determinante ser diferente de zero

In [11]:
matriz = np.array([[-2,5,3], [3,9,6], [7,8,4]])
matriz

array([[-2,  5,  3],
       [ 3,  9,  6],
       [ 7,  8,  4]])

In [12]:
np.linalg.det(matriz) # Det(A) diferente de 0, logo, tem matriz inversa

57.00000000000001

In [13]:
matriz_inv = np.linalg.inv(matriz) # Calculando matriz inversa

In [15]:
np.dot(matriz, matriz_inv) # Resulta a matriz identidade

array([[ 1.00000000e+00,  0.00000000e+00, -4.44089210e-16],
       [ 6.66133815e-16,  1.00000000e+00, -4.44089210e-16],
       [ 4.44089210e-16,  0.00000000e+00,  1.00000000e+00]])

- Exemplo:

In [18]:
B = np.array([[1,-1],[0,2]])
B

array([[ 1, -1],
       [ 0,  2]])

In [20]:
np.linalg.det(B)

2.0

In [22]:
B_inv = np.linalg.inv(B)
B_inv

array([[1. , 0.5],
       [0. , 0.5]])

In [24]:
np.dot(B,B_inv)

array([[1., 0.],
       [0., 1.]])

### Matriz Identidade

In [25]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])