In [1]:
import numpy as np

In [2]:
# Definindo o vetor original
v = np.array([[1], [1]])

In [3]:
# A) Rotação
theta = np.pi/4 # Ângulo de rotação em radianos
R = np.array([[np.cos(theta), -np.sin(theta)],
              [np.sin(theta), np.cos(theta)]])
rotated_v = np.dot(R, v)

# B) Encapsulamento
S = np.array([[2, 0],
              [0, 0.5]])
scaled_v = np.dot(5, v)

# C) Reflexão
F = np.array([[1, 0],
              [0, -1]])
reflected_v = np.dot(F, v)

# D) Cisalhamento
H = np.array([[1, 0.5],
              [0, 1]])
sheared_v = np.dot(H, v)

In [6]:
# Exibindo os resultados
print('A) Rotação: ')
print(rotated_v)

print('\nB) Encapsulamento: ')
print(scaled_v)

print('\nC) Reflexão: ')
print(reflected_v)

print('\nD) Cisalhamento: ')
print(sheared_v)

A) Rotação: 
[[1.11022302e-16]
 [1.41421356e+00]]

B) Encapsulamento: 
[[5]
 [5]]

C) Reflexão: 
[[ 1]
 [-1]]

D) Cisalhamento: 
[[1.5]
 [1. ]]
